export const SIRIUS_GAMES = [
    {
        date: '05.10.2024',
        time: '19:30',
        vs: 'ЛФК',
        score: [76, 51],
        stats: 'vsLFK.xlsx',
    },
    {
        date: '20.10.2024',
        time: '12:30',
        vs: 'GOLDEN HILL',
        score: [63, 64],
        stats: 'vsGoldenHill.xlsx',
    },
    {
        date: '03.11.2024',
        time: '11:00',
        vs: 'Mapogo males',
        score: [70, 77],
        stats: 'vsMapogoMales.xlsx',
    },
    {
        date: '17.11.2024',
        time: '15:30',
        vs: 'Eagles',
        score: [48, 42],
        stats: '',
    },
    {
        date: '01.12.2024',
        time: '15:30',
        vs: 'ОПЛАТИ',
        score: '',
        stats: '',
    },
    {
        date: '15.12.2024',
        time: '15:30',
        vs: 'NORD',
        score: '',
        stats: '',
    },
    {
        date: '28.12.2024',
        time: '16:30',
        vs: 'ISsoft',
        score: '',
        stats: '',
    },
    {
        date: '19.01.2025',
        time: '11:00',
        vs: 'VSS',
        score: '',
        stats: '',
    },
    {
        date: '01.02.2025',
        time: '16:30',
        vs: 'Грушвиль',
        score: '',
        stats: '',
    },
    {
        date: '16.02.2025',
        time: '11:00',
        vs: 'БГУФК',
        score: '',
        stats: '',
    },
    {
        date: '02.03.2025',
        time: '12:30',
        vs: 'Эра-Недвиж',
        score: '',
        stats: '',
    },
];